runtime: python39

instance_class: F1

env_variables:
  MSQL_USER: 'root'
  MYSQL_PASSWORD: 'password'
  MYSQL_DB: 'todo'
  MYSQL_HOST: 1.2.3.4.5

handlers: 
- url: /img
  static_dir: static/img

- url: /script
  static_dir: static/script

- url: /styles
  static_dir: static/styles